go_binary(
    name = "example",
    srcs = ["main.go"],
    deps = [
        "//src/prompts",
        "//src/prompts/colors",
        "//src/prompts/env",
        "//src/prompts/git",
        "//src/prompts/k8s",
    ],
)
