go_binary(
    name = 'my-prompt',
    srcs = ['main.go'],
    deps = [
        '//src/git',
        '//src/k8s',
        '//src/prompts',
        '//src/zsh',
        '//third_party:flags',
    ],
)
