go_library(
    name = "prompts",
    srcs = [
        "component.go",
        "dynamic.go",
        "end.go",
        "func.go",
        "opts.go",
        "prompts.go",
        "static.go",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//deps:flags",
    ],
)
