go_library(
    name = 'prompts',
    srcs = [
        'component.go',
        'dynamic.go',
        'end.go',
        'static.go',
        'opts.go',
        'prompts.go',
        'func.go',
    ],
    deps = [
        '//deps:flags',
    ],
    visibility = ['PUBLIC'],
)
